name = "Continuation"
uuid = "237b44e8-ee00-45b5-a0e2-fa267ed9b7fc"
authors = ["Martin Bataille"]
version = "0.1.0"

[compat]
julia = "1.6.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
